### ISSUE TITLE
Crash for "jupyter~=1.0.0"

### ISSUE THREAD

**Issue by bcm-at-zama** [pypa/pip-audit#534] opened 2023-03-01 18:41 UTC
## Bug description

I do a `pip-audit -r requirements.txt`. It crashes, on my macOS.

## Reproduction steps

```
 1896  python3.8 -m venv .venv38
 1897  source .venv38/bin/activate
 1898  pip install pip-audit
 1900  echo "torch==1.12.1" > requirements.txt
 1901  pip-audit -r requirements.txt
```

It works!

```
 1902  echo "jupyter~=1.0.0" > requirements.txt
 1903  pip-audit -r requirements.txt
```

It fails:

<details>
pip-audit -r requirements.txt     
WARNING:pip_audit._dependency_source.resolvelib.pypi_provider:invalid specifier set for Python version: >=2.7,!=3.0*,!=3.1*,!=3.2*
WARNING:pip_audit._dependency_source.resolvelib.pypi_provider:invalid specifier set for Python version: >=2.7,!=3.0*,!=3.1*,!=3.2*
(...)
WARNING:pip_audit._dependency_source.resolvelib.pypi_provider:invalid specifier set for Python version: >=2.7,!=3.0*,!=3.1*,!=3.2*
WARNING:pip_audit._dependency_source.resolvelib.pypi_provider:invalid specifier set for Python version: >=2.7,!=3.0*,!=3.1*,!=3.2*
WARNING:pip_audit._dependency_source.resolvelib.pypi_provider:invalid specifier set for Python version: >=2.7,!=3.0*,!=3.1*,!=3.2*
WARNING:pip_audit._dependency_source.resolvelib.pypi_provider:invalid specifier set for Python version: >=2.7,!=3.0*,!=3.1*,!=3.2*
WARNING:pip_audit._dependency_source.resolvelib.pypi_provider:invalid specifier set for Python version: >=2.7,!=3.0*,!=3.1*,!=3.2*
Traceback (most recent call last):
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/packaging/requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/packaging/_parser.py", line 120, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/packaging/_parser.py", line 209, in _parse_specifier
    tokenizer.consume("WS")
  File "/usr/local/Cellar/python@3.8/3.8.15/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/packaging/_tokenizer.py", line 183, in enclosing_tokens
    self.raise_syntax_error(
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/packaging/_tokenizer.py", line 163, in raise_syntax_error
    raise ParserSyntaxError(
packaging._tokenizer.ParserSyntaxError: Expected closing RIGHT_PARENTHESIS
    sys-platform (=="darwin") ; extra == 'objc'
                 ~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/bin/pip-audit", line 8, in <module>
    sys.exit(audit())
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/pip_audit/_cli.py", line 455, in audit
    for (spec, vulns) in auditor.audit(source):
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/pip_audit/_audit.py", line 67, in audit
    for dep, vulns in self._service.query_all(specs):
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/pip_audit/_service/interface.py", line 155, in query_all
    for spec in specs:
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/pip_audit/_dependency_source/requirement.py", line 116, in collect
    for _, dep in self._collect_cached_deps(filename, reqs):
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/pip_audit/_dependency_source/requirement.py", line 328, in _collect_cached_deps
    for req, resolved_deps in self._resolver.resolve_all(iter(req_values)):
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/pip_audit/_dependency_source/interface.py", line 88, in resolve_all
    yield (req, self.resolve(req))
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/pip_audit/_dependency_source/resolvelib/resolvelib.py", line 78, in resolve
    result = self.resolver.resolve([req])
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/resolvelib/resolvers.py", line 521, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/resolvelib/resolvers.py", line 402, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/resolvelib/resolvers.py", line 238, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/resolvelib/resolvers.py", line 228, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/pip_audit/_dependency_source/resolvelib/pypi_provider.py", line 435, in get_dependencies
    return candidate.dependencies
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/pip_audit/_dependency_source/resolvelib/pypi_provider.py", line 126, in dependencies
    self._dependencies = list(self._get_dependencies())
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/pip_audit/_dependency_source/resolvelib/pypi_provider.py", line 112, in _get_dependencies
    r = Requirement(d)
  File "/Users/benoitchevalliermames/Documents/Zama/Git/concrete-ml-internal/benoit/.venv38/lib/python3.8/site-packages/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
    sys-platform (=="darwin") ; extra == 'objc'
                 ~^
</details>

## Expected behavior

I guess ~ is not managed as expected. 

## Screenshots and logs

See above

## Platform information

* OS name and version: macOS

```
sw_vers
ProductName:	macOS
ProductVersion:	12.6.3
BuildVersion:	21G419
```

* `pip-audit` version (`pip-audit -V`): pip-audit 2.4.14 
* Python version (`python -V` or `python3 -V`): Python 3.8.15
* `pip` version (`pip -V` or `pip3 -V`): pip 22.0.4

**Comment by woodruffw** [comment] 2023-03-05 03:40
Thanks for the report, and sorry for the delayed response!

> I guess ~ is not managed as expected.

The traceback indicates that the error isn't with `~`, but with a subdependency that has an invalid specifier:

```
packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
sys-platform (=="darwin") ; extra == 'objc'
~^
```

Could you run `pip-audit` with `-vv` and paste the detailed logs here?

**Comment by bcm-at-zama** [comment] 2023-03-06 09:04
Sure, here is the file for `pip-audit -r requirements.txt -vv`: 
[crash.txt](https://github.com/pypa/pip-audit/files/10896186/crash.txt)

Thanks for your help

**Comment by woodruffw** [comment] 2023-03-08 16:15
I think this was fixed with #523, since that changeset completely refactored how we handle requirements resolution. The fix there is blocked by some other behavior, which I'm fixing in #536.

**Comment by woodruffw** [comment] 2023-03-08 16:47
@fd0r @bcm-at-zama could one of you try with the latest `main` and let me know if the changes there fix the issue for you? I can't reproduce the crash with the changes there; if it's the same for you, we'll prioritize making a release once we also get a fix introduced for the regression identified in #537.

**Comment by fd0r** [comment] 2023-03-08 16:57
Thanks, I'll check and come back to you! 🙏🏼

**Comment by fd0r** [comment] 2023-03-08 16:59
It appears that the bug is fixed when using main, thanks a lot! 🙏🏼

**Comment by woodruffw** [comment] 2023-03-08 17:06
Glad to hear it! We'll try to get a release out with the fix pretty soon.

**Comment by bcm-at-zama** [comment] 2023-03-08 17:53
Thanks a lot! So, should I close the issue now, or wait it is released? Your choice

**Comment by woodruffw** [comment] 2023-03-08 17:56
> Thanks a lot! So, should I close the issue now, or wait it is released? Your choice

We'll close it when we make the release 🙂

**Comment by woodruffw** [comment] 2023-03-13 15:14
Closing in prep for a 2.5.0 release. Thanks again for reporting!

**Closed by woodruffw** 2023-03-13 15:14 UTC
Labels: bug, component:dep-sources
